### PR TITLE
Prac 06 feedback

### PR DESCRIPTION
**Pull request by Shad-Man99**
PLease check my work @tahliaclennar23

### CODE REVIEW

**Comment by tahliaclennar23** [comment]
When making cost an input it should be added as a float. for example cost = float(input(Cost: ))

**Comment by tahliaclennar23** [comment]
Add a docstring when you define your main.

**Comment by tahliaclennar23** [comment]
Add a relevant docstring at the start to introduce the program.

**Comment by tahliaclennar23** [comment]
Adding commits through every small milestone is best. I can only see 4 commits.

**Comment by tahliaclennar23** [comment]
Underneath your functions there should be a docstring that completes the sentence "this function will...."
Some of the docstrings i've seen do not follow this way.

**Comment by lindsaymarkward** [comment]
@tahliaclennar23 - Thanks for doing this code review 👍 
Can I ask you to use the inline comments feature instead of adding comments just in the conversation? That is, click the + button on the relevant line of code. This helps match the feedback to the code. Thanks!

**Comment by Shad-Man99** [comment]
Will do.
________________________________

**Pull request merged**
